"""Shared engineering-unit conversion helpers for Sampler.

The module is dependency-free and is used by both the command-line and web
interfaces.  Conversion rules are explicit: a column, physical quantity,
source unit, and target unit must be selected before values are changed.
"""

from __future__ import annotations

import csv
import io
import math
import re
import unicodedata
from dataclasses import dataclass
from typing import Any, Iterable


@dataclass(frozen=True)
class ConversionRule:
    column_index: int
    quantity: str
    from_unit: str
    to_unit: str


# ``factor`` converts a value to the base unit of each linear quantity.
# Temperature uses affine scale/offset parameters generated by
# ``unit_affine_parameters`` and follows the same shared conversion path.
UNIT_CATALOG: dict[str, dict[str, Any]] = {
    "airflow": {
        "label": "풍량",
        "units": {
            "cms": {
                "label": "CMS (m³/s)",
                "header": "CMS",
                "factor": 1.0,
                "aliases": (
                    "cms", "m3/s", "m^3/s", "m³/s", "m3/sec", "m3/second",
                    "m3s-1", "m3ps", "cubic meter per second",
                    "cubic metre per second",
                ),
            },
            "cmm": {
                "label": "CMM (m³/min)",
                "header": "CMM",
                "factor": 1.0 / 60.0,
                "aliases": (
                    "cmm", "m3/min", "m^3/min", "m³/min", "m3/minute",
                    "m3min-1", "cubic meter per minute", "cubic metre per minute",
                ),
            },
            "cmh": {
                "label": "CMH (m³/h)",
                "header": "CMH",
                "factor": 1.0 / 3600.0,
                "aliases": (
                    "cmh", "m3/h", "m^3/h", "m³/h", "m3/hr", "m3/hour",
                    "m3h-1", "cubic meter per hour", "cubic metre per hour",
                ),
            },
        },
    },
    "temperature": {
        "label": "온도",
        "units": {
            "k": {
                "label": "K",
                "header": "K",
                "aliases": ("k", "kelvin", "degk", "degree k", "degrees k", "°k"),
            },
            "degc": {
                "label": "degC (°C)",
                "header": "degC",
                "aliases": (
                    "degc", "°c", "℃", "celsius", "degree c", "degrees c",
                    "degreec", "c",
                ),
            },
        },
    },
    "humidity": {
        "label": "습도",
        "units": {
            "fraction": {
                "label": "소수 (0–1)",
                "header": "decimal",
                "factor": 1.0,
                "aliases": ("fraction", "decimal", "ratio", "0-1", "0to1", "frac"),
            },
            "percent": {
                "label": "%",
                "header": "%",
                "factor": 0.01,
                "aliases": ("%", "percent", "percentage", "pct"),
            },
        },
    },
    "time": {
        "label": "시간",
        "units": {
            "ns": {
                "label": "ns",
                "header": "ns",
                "factor": 1e-9,
                "aliases": ("ns", "nsec", "nsecs", "nanosecond", "nanoseconds"),
            },
            "us": {
                "label": "µs",
                "header": "us",
                "factor": 1e-6,
                "aliases": (
                    "us", "µs", "μs", "usec", "usecs", "microsecond", "microseconds",
                ),
            },
            "ms": {
                "label": "ms",
                "header": "ms",
                "factor": 1e-3,
                "aliases": ("ms", "msec", "msecs", "millisecond", "milliseconds"),
            },
            "s": {
                "label": "sec",
                "header": "sec",
                "factor": 1.0,
                "aliases": ("s", "sec", "secs", "second", "seconds"),
            },
            "min": {
                "label": "min",
                "header": "min",
                "factor": 60.0,
                "aliases": ("min", "mins", "minute", "minutes"),
            },
            "h": {
                "label": "hr",
                "header": "hr",
                "factor": 3600.0,
                "aliases": ("h", "hr", "hrs", "hour", "hours"),
            },
        },
    },
}

_QUANTITY_NAME_HINTS: dict[str, tuple[str, ...]] = {
    "airflow": (
        "airflow", "airflowrate", "volumeflow", "volumetricflow",
        "volumeflowrate", "qair", "풍량",
    ),
    "temperature": ("temperature", "temp", "airtemp", "watertemp", "온도"),
    "humidity": ("relativehumidity", "humidity", "rh", "습도"),
    "time": (
        "flowtime", "elapsedtime", "simulationtime", "physicaltime", "timestamp",
        "datetime", "timestep", "time", "시간",
    ),
}

_BRACKETED_SUFFIX = re.compile(
    r"(?P<open>[\(\[\{])\s*(?P<inner>[^\)\]\}]+?)\s*(?P<close>[\)\]\}])\s*$"
)
_SUFFIX_SEPARATOR = re.compile(r"[\s_\-/]+")


def _normalize_unit_token(value: str) -> str:
    text = unicodedata.normalize("NFKC", str(value)).strip().lower()
    text = text.replace("℃", "degc").replace("°c", "degc").replace("°k", "degk")
    text = text.replace("µ", "u").replace("μ", "u")
    text = text.replace("³", "3").replace("^3", "3")
    text = text.replace("per", "/")
    text = re.sub(r"\s+", "", text)
    text = text.strip("()[]{}")
    return text


def _normalize_name(value: str) -> str:
    text = unicodedata.normalize("NFKC", str(value)).strip().lower()
    text = text.replace("℃", "degc").replace("°c", "degc")
    return re.sub(r"[^0-9a-z가-힣]+", "", text)


def quantity_ids() -> tuple[str, ...]:
    return tuple(UNIT_CATALOG)


def unit_ids(quantity: str) -> tuple[str, ...]:
    validate_quantity(quantity)
    return tuple(UNIT_CATALOG[quantity]["units"])


def validate_quantity(quantity: str) -> None:
    if quantity not in UNIT_CATALOG:
        raise ValueError(f"지원하지 않는 물리량입니다: {quantity}")


def validate_unit(quantity: str, unit: str) -> None:
    validate_quantity(quantity)
    if unit not in UNIT_CATALOG[quantity]["units"]:
        raise ValueError(
            f"{UNIT_CATALOG[quantity]['label']}에서 지원하지 않는 단위입니다: {unit}"
        )


def validate_rule(rule: ConversionRule, column_count: int | None = None) -> None:
    if column_count is not None and not 0 <= rule.column_index < column_count:
        raise ValueError(
            f"변환 열 번호 {rule.column_index}가 유효 범위 0..{column_count - 1}을 벗어났습니다."
        )
    validate_unit(rule.quantity, rule.from_unit)
    validate_unit(rule.quantity, rule.to_unit)
    if rule.from_unit == rule.to_unit:
        raise ValueError("변환 전 단위와 변환 후 단위는 서로 달라야 합니다.")


def make_rule(
    column_index: int,
    quantity: str,
    from_unit: str,
    to_unit: str,
    column_count: int | None = None,
) -> ConversionRule:
    rule = ConversionRule(
        column_index=int(column_index),
        quantity=str(quantity).strip().lower(),
        from_unit=str(from_unit).strip().lower(),
        to_unit=str(to_unit).strip().lower(),
    )
    validate_rule(rule, column_count)
    return rule


def unit_affine_parameters(quantity: str, unit: str) -> tuple[float, float]:
    """Return ``(scale, offset)`` for converting a unit to its quantity base.

    ``base_value = source_value * scale + offset``.  The base units are CMS,
    degC, decimal humidity, and seconds.
    """

    validate_unit(quantity, unit)
    if quantity == "temperature":
        return (1.0, -273.15) if unit == "k" else (1.0, 0.0)
    return float(UNIT_CATALOG[quantity]["units"][unit]["factor"]), 0.0


def catalog_payload() -> list[dict[str, Any]]:
    payload: list[dict[str, Any]] = []
    for quantity, specification in UNIT_CATALOG.items():
        unit_payload: list[dict[str, Any]] = []
        for unit, unit_spec in specification["units"].items():
            scale, offset = unit_affine_parameters(quantity, unit)
            unit_payload.append(
                {
                    "id": unit,
                    "label": unit_spec["label"],
                    "header": unit_spec["header"],
                    "scale": scale,
                    "offset": offset,
                }
            )
        payload.append(
            {
                "id": quantity,
                "label": specification["label"],
                "units": unit_payload,
            }
        )
    return payload


def resolve_unit_token(value: str, quantity: str | None = None) -> tuple[str, str]:
    """Resolve a unit token to ``(quantity, canonical_unit)``.

    A quantity can be supplied to disambiguate short tokens such as ``h`` or
    ``c``.  Tokens are matched exactly after Unicode and whitespace
    normalization, preventing accidental matches inside column names.
    """

    normalized = _normalize_unit_token(value)
    quantities: Iterable[str] = (quantity,) if quantity else UNIT_CATALOG.keys()
    matches: list[tuple[str, str]] = []
    for quantity_id in quantities:
        if quantity_id is None:
            continue
        validate_quantity(quantity_id)
        for unit_id, unit_spec in UNIT_CATALOG[quantity_id]["units"].items():
            aliases = {_normalize_unit_token(unit_id), _normalize_unit_token(unit_spec["header"])}
            aliases.update(_normalize_unit_token(alias) for alias in unit_spec["aliases"])
            if normalized in aliases:
                matches.append((quantity_id, unit_id))
    if not matches:
        scope = f" ({quantity})" if quantity else ""
        raise ValueError(f"지원하지 않는 단위입니다{scope}: {value}")
    if len(matches) > 1:
        raise ValueError(f"단위가 여러 물리량과 겹칩니다. 물리량을 지정해 주세요: {value}")
    return matches[0]


def _suffix_candidates(header: str) -> list[tuple[str, int, str]]:
    """Return possible trailing unit tokens as ``(token, start, separator)``.

    Candidates are longest-first.  For ``Airflow_m3/s`` this includes ``m3/s``
    before ``s``, allowing the volumetric-flow unit to win.
    """

    candidates: list[tuple[str, int, str]] = []
    for match in _SUFFIX_SEPARATOR.finditer(header):
        token = header[match.end():].strip()
        if token:
            candidates.append((token, match.start(), match.group(0)))
    candidates.sort(key=lambda item: len(item[0]), reverse=True)
    return candidates


def detect_header_unit(header: str) -> tuple[str, str] | None:
    text = str(header).strip().strip('"').strip("'")
    if not text:
        return None

    bracket = _BRACKETED_SUFFIX.search(text)
    if bracket:
        try:
            return resolve_unit_token(bracket.group("inner"))
        except ValueError:
            pass

    for token, _, _ in _suffix_candidates(text):
        try:
            return resolve_unit_token(token)
        except ValueError:
            continue

    try:
        return resolve_unit_token(text)
    except ValueError:
        return None


def header_base_text(header: str) -> str:
    """Return a header label with a recognized trailing unit removed."""

    text = str(header).strip().strip('"').strip("'")
    if not text:
        return text

    bracket = _BRACKETED_SUFFIX.search(text)
    if bracket:
        try:
            resolve_unit_token(bracket.group("inner"))
            return text[: bracket.start()].rstrip()
        except ValueError:
            pass

    for token, start, _ in _suffix_candidates(text):
        try:
            resolve_unit_token(token)
            return text[:start].rstrip()
        except ValueError:
            continue

    return "" if detect_header_unit(text) else text


def detect_quantity_from_name(header: str) -> str | None:
    normalized = _normalize_name(header)
    for quantity, hints in _QUANTITY_NAME_HINTS.items():
        if any(hint == normalized or hint in normalized for hint in hints):
            return quantity
    return None


def header_hint(
    header: str,
    *,
    is_time_column: bool = False,
    parsed_time_unit: str | None = None,
) -> dict[str, str | None] | None:
    if is_time_column:
        source_unit = parsed_time_unit or "s"
        if source_unit in UNIT_CATALOG["time"]["units"]:
            return {"quantity": "time", "unit": source_unit, "detected": "time-column"}

    detected = detect_header_unit(header)
    if detected:
        quantity, unit = detected
        return {"quantity": quantity, "unit": unit, "detected": "header-unit"}

    quantity = detect_quantity_from_name(header)
    if quantity:
        return {"quantity": quantity, "unit": None, "detected": "column-name"}
    return None


def convert_value(value: float, quantity: str, from_unit: str, to_unit: str) -> float:
    validate_unit(quantity, from_unit)
    validate_unit(quantity, to_unit)
    if not math.isfinite(value):
        raise ValueError("NaN 또는 Infinity 값은 단위변환할 수 없습니다.")
    if from_unit == to_unit:
        return value

    source_scale, source_offset = unit_affine_parameters(quantity, from_unit)
    target_scale, target_offset = unit_affine_parameters(quantity, to_unit)
    base_value = value * source_scale + source_offset
    result = (base_value - target_offset) / target_scale

    if not math.isfinite(result):
        raise ValueError("단위변환 결과가 유효한 숫자가 아닙니다.")
    return result


def format_number(value: float) -> str:
    if abs(value) < 1e-15:
        value = 0.0
    return format(value, ".15g")


def convert_text(value: str, rule: ConversionRule, row_number: int | None = None) -> str:
    stripped = str(value).strip()
    if not stripped:
        return value
    number_text = stripped.strip('"').strip("'")
    try:
        number = float(number_text)
    except ValueError as exc:
        location = f" (데이터 행 {row_number})" if row_number is not None else ""
        raise ValueError(
            f"{rule.column_index + 1}번째 열의 값 '{value}'은 숫자가 아니어서 "
            f"단위변환할 수 없습니다{location}."
        ) from exc
    converted = convert_value(number, rule.quantity, rule.from_unit, rule.to_unit)
    return format_number(converted)


def apply_rules_to_fields(
    fields: list[str],
    rules: Iterable[ConversionRule],
    *,
    row_number: int | None = None,
) -> list[str]:
    output = list(fields)
    for rule in rules:
        if rule.column_index >= len(output):
            location = f" (데이터 행 {row_number})" if row_number is not None else ""
            raise ValueError(
                f"{rule.column_index + 1}번째 변환 열이 데이터에 없습니다{location}."
            )
        output[rule.column_index] = convert_text(
            output[rule.column_index], rule, row_number=row_number
        )
    return output


def unit_header_label(quantity: str, unit: str) -> str:
    validate_unit(quantity, unit)
    return str(UNIT_CATALOG[quantity]["units"][unit]["header"])


def replace_header_unit(header: str, rule: ConversionRule) -> str:
    """Replace a recognized trailing source unit while retaining header style."""

    validate_rule(rule)
    text = str(header).strip()
    if not text:
        return text
    target = unit_header_label(rule.quantity, rule.to_unit)

    bracket = _BRACKETED_SUFFIX.search(text)
    if bracket:
        try:
            detected = resolve_unit_token(bracket.group("inner"), rule.quantity)
        except ValueError:
            detected = None
        # The user's selected source unit is authoritative. If the header has
        # any recognized unit for the same quantity, replace it rather than
        # producing a contradictory label such as ``Temperature(K) (degC)``.
        if detected and detected[0] == rule.quantity:
            return (
                text[: bracket.start("inner")]
                + target
                + text[bracket.end("inner") :]
            )

    for token, start, separator in _suffix_candidates(text):
        try:
            detected = resolve_unit_token(token, rule.quantity)
        except ValueError:
            continue
        if detected and detected[0] == rule.quantity:
            return text[:start].rstrip() + separator + target

    try:
        detected = resolve_unit_token(text, rule.quantity)
    except ValueError:
        detected = None
    if detected and detected[0] == rule.quantity:
        return target

    # The user can explicitly define a source unit even when the header has no
    # unit.  Appending the target prevents an unlabeled converted column.
    return f"{text} ({target})"


def converted_headers(headers: list[str], rules: Iterable[ConversionRule]) -> list[str]:
    output = list(headers)
    for rule in rules:
        if rule.column_index >= len(output):
            raise ValueError(f"헤더에 {rule.column_index + 1}번째 변환 열이 없습니다.")
        output[rule.column_index] = replace_header_unit(output[rule.column_index], rule)
    return output


def serialize_fields(
    fields: list[str],
    delimiter: str,
    *,
    template_line: str | None = None,
    is_header: bool = False,
) -> str:
    """Serialize fields using the source delimiter.

    Whitespace reports (including Fluent report files) retain optional wrapping
    parentheses.  If the original header quoted its labels, all generated header
    labels are quoted as well.
    """

    wrapper = False
    quote_all = False
    if template_line is not None:
        stripped = template_line.strip()
        wrapper = stripped.startswith("(") and stripped.endswith(")")
        quote_all = is_header and ('"' in template_line or "'" in template_line)

    if delimiter != "whitespace":
        stream = io.StringIO(newline="")
        writer = csv.writer(stream, delimiter=delimiter, lineterminator="")
        writer.writerow(fields)
        line = stream.getvalue()
    else:
        serialized: list[str] = []
        for field in fields:
            value = str(field)
            needs_quote = quote_all or bool(re.search(r"\s", value)) or '"' in value
            if needs_quote:
                value = '"' + value.replace('"', '\\"') + '"'
            serialized.append(value)
        line = " ".join(serialized)

    return f"({line})" if wrapper else line


def formula_text(quantity: str, from_unit: str, to_unit: str) -> str:
    """Return a compact human-readable conversion formula for documentation/UI."""

    validate_unit(quantity, from_unit)
    validate_unit(quantity, to_unit)
    if from_unit == to_unit:
        return "변환 없음"

    source_scale, source_offset = unit_affine_parameters(quantity, from_unit)
    target_scale, target_offset = unit_affine_parameters(quantity, to_unit)
    multiplier = source_scale / target_scale
    intercept = (source_offset - target_offset) / target_scale
    if abs(multiplier - 1.0) < 1e-12 and abs(intercept) > 1e-12:
        sign = "+" if intercept > 0 else "−"
        return f"값 {sign} {format(abs(intercept), '.8g')}"
    if abs(intercept) < 1e-12:
        if abs(multiplier - round(multiplier)) < 1e-12:
            return f"값 × {format(round(multiplier), 'g')}"
        reciprocal = round(1.0 / multiplier) if multiplier else 0
        if reciprocal and abs(multiplier - 1.0 / reciprocal) < 1e-12:
            return f"값 ÷ {format(reciprocal, 'g')}"
        return f"값 × {format(multiplier, '.8g')}"
    return f"값 × {format(multiplier, '.8g')} + {format(intercept, '.8g')}"
